image: docker:latest

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

stages:
  - test
  - build
  - image
  - deploy

services:
  - docker:dind

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: node:14
  retry: 2
  script:
    - npm install
    - npm run lint
    - npm test
  artifacts:
    when: always
    reports:
      junit: reports/**/*.xml

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

images:
  stage: image
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t eletraenergy/Offenders-frontend:latest .
    - docker push eletraenergy/Offenders-frontend:latest

deploy:
  stage: deploy
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker pull eletraenergy/Offenders-frontend:latest
    - docker run -d -p 80:80 eletraenergy/Offenders-frontend:latest
  when: manual
  tags:
    - docker
